core/core/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views
from django.conf.urls.static import static
from django.conf import settings

from django.urls import re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Todo app API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="matinnjt2000@gmail.com"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)
urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", views.HomePageView.as_view(), name="homepage"),
    path("tasks/", include("task.urls")),
    path("weather/", include("weather.urls")),
]
swagger_routes = [
    path(
        "swagger<format>/",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]
urlpatterns += swagger_routes
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/task/api/v1/urls.py
from rest_framework.routers import DefaultRouter
from . import views

app_name = "api-v1"
router = DefaultRouter()
router.register("task", views.TaskListModelViewSet, "task")
urlpatterns = []
urlpatterns += router.urls

core/task/urls.py
from django.urls import path, include
from . import views

app_name = "tasks"
urlpatterns = [
    path("list/", views.TaskListView.as_view(), name="task-list"),
    path(
        "<int:pk>/details",
        views.TaskDetailView.as_view(),
        name="task-detail",
    ),
    path("<int:pk>/edit", views.TaskEditView.as_view(), name="task-edit"),
    path(
        "<int:pk>/delete", views.TaskDeleteView.as_view(), name="task-delete"
    ),
    path("create/", views.TaskCreateView.as_view(), name="task-create"),
    path(
        "update_task_status/<int:pk>",
        views.update_status,
        name="update_task_status",
    ),
    path("api/v1/", include("task.api.v1.urls")),
]

core/task/models.py
from django.db import models


class TaskStatus(models.TextChoices):
    NEW = "NEW", "new"
    DONE = "DONE", "done"


# Create your models here.
class Task(models.Model):
    author = models.ForeignKey(
        "accounts.Profile", on_delete=models.CASCADE, related_name="tasks"
    )
    title = models.CharField(max_length=255)
    status = models.CharField(
        choices=TaskStatus.choices, default=TaskStatus.NEW, max_length=255
    )

    def __str__(self):
        return f"{self.author}  {self.title}"

core/task/api/v1/views.py
import sys

from rest_framework.viewsets import GenericViewSet, ModelViewSet
from rest_framework.decorators import action
from rest_framework.response import Response
from task.models import Task
from rest_framework.permissions import IsAuthenticated
from .serializers import TaskSerializer
from .paginations import DefaultPagination
from rest_framework.filters import SearchFilter
from django_filters.rest_framework import DjangoFilterBackend


class TaskListModelViewSet(ModelViewSet):
    permission_classes = [IsAuthenticated]
    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    pagination_class = DefaultPagination
    filter_backends = [DjangoFilterBackend, SearchFilter]
    filterset_fields = ["title"]
    search_fields = ["title", "author__first_name"]
    lookup_field = "id"

    def get_queryset(self):
        return self.queryset.filter(author=self.request.user.profile)

    def perform_create(self, serializer):
        serializer.save(author=self.request.user.profile)

    def perform_update(self, serializer):
        serializer.save(author=self.request.user.profile)

    def perform_destroy(self, instance):
        if instance.author.user == self.request.user:
            return super().perform_destroy(instance)

core/task/views.py
import sys
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from .models import Task
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from rest_framework.viewsets import GenericViewSet
from django.urls import reverse


# Create your views here.
class TaskListView(ListView):
    def get_queryset(self):
        tasks = Task.objects.filter(author=self.request.user.profile)
        return tasks


class TaskCreateView(CreateView, LoginRequiredMixin):
    login_url = "/accounts/login/"
    model = Task
    fields = ["title"]
    success_url = "/tasks/list/"

    def form_valid(self, form):
        form.instance.author = self.request.user.profile
        return super().form_valid(form)


class TaskDetailView(DetailView):
    queryset = Task.objects.all()


class TaskEditView(UpdateView):
    queryset = Task.objects.all()
    fields = ["title", "status"]
    success_url = "/tasks/list/"


class TaskDeleteView(DeleteView):
    queryset = Task.objects.all()
    success_url = "/tasks/list/"


def update_status(request, pk):
    if request.method == "POST":
        obj = get_object_or_404(Task, pk=pk)
        new_status = request.POST.get("status")
        if new_status in ["NEW", "DONE"]:  # Ensure valid status
            obj.status = new_status
            obj.save()
            return redirect(reverse("tasks:task-detail", kwargs={'pk':pk}))
        else:
            return HttpResponse("Invalid status", status=400)
    return HttpResponse("Invalid request method", status=405)

core/templates/task/task_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Task</title>
</head>
<body>
<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>
</body>
</html>

core/templates/task/task_detail.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Task Details</title>
</head>
<body>
    <h1>ID: {{ object.id }}</h1>
    <p>Title: {{ object.title }}</p>
    <p>Status: {{ object.status }}</p>
    <form method="post" action="{% url 'tasks:update_task_status' object.id %}">
        {% csrf_token %}
        <label for="status">Status:</label>
        <select name="status" id="status">
            <option value="DONE" {% if object.status == 'DONE' %}selected{% endif %}>Done</option>
            <option value="NEW" {% if object.status == 'NEW' %}selected{% endif %}>New</option>
        </select>
        <button type="submit">Change Status</button>
    </form>
</body>
</html>

core/templates/task/task_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Task</title>
</head>
<body>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>
</body>
</html>

core/templates/task/task_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Task Lists</title>
</head>
<body>
{% for task in object_list %}
    {{ task.id }} <br>
<span style="margin-right: 20px;">
    <a href="{% url 'tasks:task-detail' pk=task.id %}">{{ task.title }}</a>
</span>
<span>{{ task.status }}</span>

    <br>
    Author: {{ task.author }} <br>
    <a href="{% url 'tasks:task-edit' pk=task.id %}">Edit</a>
    <a href="{% url 'tasks:task-delete' pk=task.id %}">Delete</a>
    <hr>
{% endfor %}
<a href="{% url 'tasks:task-create' %}">Create Task</a>
<form action="{% url 'accounts:logout' %}" method="post">
    {% csrf_token %}
    <button type="submit">logout</button>
</form>
</body>
</html>